### ISSUE TITLE
Hashtag/text errors while in Japanese mode

### ISSUE THREAD

**Issue by hhkitsune** [pulibrary/openpublishing#41]
## Due Date

Suggested: 4/22 (not on fire, but we appreciate timely attention to this)

## Description

We are seeing text errors while in the Japanese language mode. Follow these steps:

1. Go to: https://ojs-staging.princeton.edu/index.php/tj1
2. Select Japanese language (top, left corner)
3. Refer to the images below for details of the errors

## Acceptance Criteria

- [ ] The identified page errors will be resolved

### The tab shows hashtags with "manager announcements"

![Screen Shot 2022-04-18 at 3 37 19 PM](https://user-images.githubusercontent.com/50670293/163879877-c9950d69-96df-432a-9a21-a7546bbf8bd8.jpeg)

### The announcement has hashtags with "common more"

![Screen Shot 2022-04-18 at 3 37 27 PM](https://user-images.githubusercontent.com/50670293/163879983-86260812-b2c9-49fc-9591-de99f265e8c9.jpeg)

### The second article has hastags with "common.commaListSeparator"

![Screen Shot 2022-04-18 at 3 37 38 PM](https://user-images.githubusercontent.com/50670293/163880205-f61e7d15-a6c1-47d8-8cf5-904d067b5e58.jpeg)

**Comment by kelynch** [comment]
This is due to the fact that there are terms missing from the Japanese language translation files associated with OJS.  

According to documentation, OJS language translations are entirely community-created and many of them are partially incomplete.  A list of languages supported in the program and their completeness of translation can be seen here - 

https://translate.pkp.sfu.ca/projects/ojs/#languages

PKP is very grateful for help making translations more complete; here is the page on their website detailing where and how translations can be contributed to the project - https://pkp.sfu.ca/contributors/translation/ 

If there is bandwidth for this, I would suggest that the Japanese language translation for OJS be expanded and contributed back to the project.  In the short term to remove the visible error, the menu itself could be updated to remove the "Announcements" page in favor of a different link if desired.  

I'm happy to discuss the path forward further and/or demo what I saw investigating this!
